import { NextResponse } from "next/server"
import { supabase, TABLES, getServiceClient } from "@/lib/supabase"
import { requirePermission, requireAuth } from "@/lib/auth/auth-helpers"

export async function GET(request: Request) {
  const auth = await requireAuth()
  if (!auth.authenticated) return auth.response
  try {
    const { searchParams } = new URL(request.url)
    const limit = Math.min(parseInt(searchParams.get("limit") || "50"), 200)
    const cursor = searchParams.get("cursor")

    let invoices: any[] = []
    let nextCursor: string | null = null
    let hasMore = false

    try {
      let query = getServiceClient()
        .from(TABLES.INVOICES)
        .select("*")
        .order("created_at", { ascending: false })
        .limit(limit + 1)

      if (cursor) {
        const { data: cursorDoc } = await getServiceClient()
          .from(TABLES.INVOICES)
          .select("created_at")
          .eq("id", cursor)
          .single()

        if (cursorDoc?.created_at) {
          query = query.lt("created_at", cursorDoc.created_at)
        }
      }

      const { data, error } = await query

      if (!error && data) {
        hasMore = data.length > limit
        invoices = data.slice(0, limit).map((doc: Record<string, any>) => ({
          id: doc.id,
          ...doc,
          created_at: doc.created_at || null,
          due_date: doc.due_date || null,
          paid_at: doc.paid_at || null,
        }))

        const lastVisible = invoices[invoices.length - 1]
        nextCursor = lastVisible ? lastVisible.id : null
      }
    } catch {
      const { data, error } = await getServiceClient()
        .from(TABLES.INVOICES)
        .select("*")
        .limit(limit)

      if (!error && data) {
        invoices = data.map((doc: Record<string, any>) => ({ id: doc.id, ...doc }))
      }
    }

    return NextResponse.json({
      success: true,
      data: invoices,
      nextCursor,
      hasMore
    })
  } catch (error) {
    console.error("Error fetching invoices:", error)
    return NextResponse.json(
      { error: "Failed to fetch invoices" },
      { status: 500 }
    )
  }
}

export async function POST(request: Request) {
  const auth = await requirePermission("invoices:create")
  if (!auth.authorized) return auth.response
  try {
    const body = await request.json()
    const {
      amount,       // Net amount
      tax_amount,   // VAT (14%)
      total_amount, // Gross amount
      cost_of_goods_sold,
      customer_id,
      customer_name,
      items,
      due_date
    } = body

    const { EnhancedAccountingService, JournalEntryType } = await import("@/lib/services/enhanced-accounting-service")

    // Generate invoice reference number
    const invoiceId = `INV-${Date.now()}`

    // Create invoice (id auto-generated by DB)
    const invoice = {
      customer_id,
      customer_name,
      amount: amount || 0,
      sales_order_id: body.sales_order_id || null,
      due_date: due_date || new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
      notes: body.notes || null,
      status: "unpaid"
    }

    // 1. Record Revenue and AR (BUG-3)
    const revenueLines = [
      {
        accountCode: "1110", // Accounts Receivable
        accountName: "Accounts Receivable",
        debit: (amount || total_amount || 0),
        credit: 0,
        description: `Invoice ${invoiceId} to ${customer_name || 'Customer'}`
      },
      {
        accountCode: "4001", // Sales Revenue
        accountName: "Sales Revenue",
        debit: 0,
        credit: amount || 0,
        description: `Net sales for ${invoiceId}`
      }
    ]

    // Add VAT if applicable (BUG-4)
    if (tax_amount > 0) {
      revenueLines.push({
        accountCode: "2110", // VAT Payable
        accountName: "VAT Payable",
        debit: 0,
        credit: tax_amount,
        description: `VAT for invoice ${invoiceId}`
      })
    }

    const revenueResult = await EnhancedAccountingService.createJournalEntry(
      JournalEntryType.SALES_INVOICE,
      revenueLines,
      invoiceId,
      `Sales recording for invoice ${invoiceId}`
    )

    if (!revenueResult.success) {
      return NextResponse.json({ error: revenueResult.error }, { status: 400 })
    }

    // 2. Record COGS (BUG-3) — auto-calculate from work order if not provided
    let cogsEntryId = null
    let finalCOGS = cost_of_goods_sold || 0

    if (finalCOGS <= 0 && body.sales_order_id) {
      try {
        // Look up completed work orders for this sales order
        const { data: woData, error: woError } = await getServiceClient()
          .from(TABLES.WORK_ORDERS)
          .select("*")
          .eq("sales_order_id", body.sales_order_id)
          .eq("status", "completed")
          .limit(1)

        if (!woError && woData && woData.length > 0) {
          const wo: any = woData[0]
          finalCOGS = wo.final_completion_cost || wo.total_cost || wo.estimated_cost || 0
        }
      } catch (err) {
        console.warn(`⚠️ Failed to auto-calculate COGS for invoice ${invoiceId}:`, err)
      }
    }

    if (finalCOGS > 0) {
      const cogsLines = [
        {
          accountCode: "5301", // Cost of Goods Sold
          accountName: "Cost of Goods Sold",
          debit: finalCOGS,
          credit: 0,
          description: `COGS for invoice ${invoiceId}`
        },
        {
          accountCode: "1220", // Finished Goods Inventory
          accountName: "Finished Goods Inventory",
          debit: 0,
          credit: finalCOGS,
          description: `Inventory reduction for ${invoiceId}`
        }
      ]

      const cogsResult = await EnhancedAccountingService.createJournalEntry(
        JournalEntryType.SALES_COGS,
        cogsLines,
        invoiceId,
        `COGS recording for invoice ${invoiceId}`
      )

      if (cogsResult.success) {
        cogsEntryId = cogsResult.entryId
      } else {
        console.warn(`⚠️ COGS entry failed for invoice ${invoiceId}: ${cogsResult.error}`)
      }
    } else {
       console.warn(`⚠️ No COGS available for invoice ${invoiceId}. Skipping COGS journal entry.`)
    }

    // Save invoice to database
    await getServiceClient()
      .from(TABLES.INVOICES)
      .insert(invoice)

    return NextResponse.json({
      ...invoice,
      revenueJournalEntryId: revenueResult.entryId,
      cogsJournalEntryId: cogsEntryId
    })
  } catch (error) {
    console.error("Error creating invoice:", error)
    return NextResponse.json(
      { error: "Failed to create invoice" },
      { status: 500 }
    )
  }
}

// PUT endpoint removed to ensure journal entry immutability (BUG-011)
