/**
 * Account Types and Chart of Accounts Structure
 * TEL U ASEGH - Garment Manufacturing ERP
 */

/**
 * Account Type Classification
 */
export enum AccountType {
    ASSET = "asset",
    CONTRA_ASSET = "contra_asset",
    LIABILITY = "liability",
    EQUITY = "equity",
    REVENUE = "revenue",
    CONTRA_REVENUE = "contra_revenue",
    COGS = "cogs",
    EXPENSE = "expense",
    OTHER = "other",
}

/**
 * Account Sub-Types for detailed classification
 */
export enum AccountSubType {
    // Assets
    CASH = "cash",
    RECEIVABLE = "receivable",
    INVENTORY = "inventory",
    PREPAID = "prepaid",
    FIXED_ASSET = "fixed_asset",
    INTANGIBLE = "intangible",
    DEPRECIATION = "depreciation",

    // Liabilities
    PAYABLE = "payable",
    TAX_PAYABLE = "tax_payable",
    ACCRUED = "accrued",
    LOAN = "loan",

    // Equity
    CAPITAL = "capital",
    RETAINED_EARNINGS = "retained_earnings",

    // Revenue
    SALES = "sales",
    SERVICE = "service",
    OTHER_INCOME = "other_income",

    // COGS
    MATERIALS = "materials",
    LABOR = "labor",
    OVERHEAD = "overhead",

    // Expenses
    OPERATING = "operating",
    ADMINISTRATIVE = "administrative",
    MARKETING = "marketing",
    FINANCIAL = "financial",
}

/**
 * Account Interface for Chart of Accounts
 */
export interface Account {
    code: string
    name: string
    nameAr?: string
    type: AccountType
    subType: AccountSubType
    normalBalance: "debit" | "credit"
    parentCode?: string
    isActive: boolean
    isSystemAccount: boolean
    isCashFlowTracked: boolean
    description?: string
    deprecatedReason?: string
}

/**
 * Complete Chart of Accounts for TEL U ASEGH Garment Manufacturing
 */
export const CHART_OF_ACCOUNTS: Record<string, Account> = {
    // ============================================
    // ASSETS (1xxx)
    // ============================================

    // Cash & Bank (1101-1104)
    "1101": {
        code: "1101",
        name: "Cash on Hand",
        nameAr: "النقدية بالصندوق",
        type: AccountType.ASSET,
        subType: AccountSubType.CASH,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: true,
        description: "Physical cash kept in store or factory for daily small payments",
    },
    "1102": {
        code: "1102",
        name: "Petty Cash",
        nameAr: "صندوق المصروفات النثرية",
        type: AccountType.ASSET,
        subType: AccountSubType.CASH,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: true,
        description: "Small operational cash for minor expenses",
    },
    "1103": {
        code: "1103",
        name: "Bank - Main Account",
        nameAr: "الحساب البنكي الرئيسي",
        type: AccountType.ASSET,
        subType: AccountSubType.CASH,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: true,
        description: "Primary business bank account for collections and payments",
    },
    "1104": {
        code: "1104",
        name: "Bank - Savings",
        nameAr: "حساب التوفير",
        type: AccountType.ASSET,
        subType: AccountSubType.CASH,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: true,
        description: "Savings or reserve bank account",
    },
    "1105": {
        code: "1105",
        name: "Bank - Payroll",
        nameAr: "حساب الرواتب البنكي",
        type: AccountType.ASSET,
        subType: AccountSubType.CASH,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: true,
        description: "Payroll disbursement account",
    },
    "1106": {
        code: "1106",
        name: "Bank - Payment Gateway",
        nameAr: "بوابة الدفع الإلكتروني",
        type: AccountType.ASSET,
        subType: AccountSubType.CASH,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: true,
        description: "Online payments/collections account",
    },
    "1107": {
        code: "1107",
        name: "Cheques Under Collection",
        nameAr: "شيكات تحت التحصيل",
        type: AccountType.ASSET,
        subType: AccountSubType.CASH,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: true,
        description: "Pending deposited cheques",
    },

    // Receivables (1110-1125)
    "1113": {
        code: "1113",
        name: "Contract Asset (Unbilled Revenue)",
        nameAr: "أصل العقد - إيراد غير مفوتر",
        type: AccountType.ASSET,
        subType: AccountSubType.RECEIVABLE,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Revenue earned but not yet billed to customer (IFRS 15 over-time recognition)",
    },
    "1110": {
        code: "1110",
        name: "Accounts Receivable - Customers",
        nameAr: "العملاء - ذمم مدينة",
        type: AccountType.ASSET,
        subType: AccountSubType.RECEIVABLE,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Amounts owed by customers for delivered orders",
    },
    "1115": {
        code: "1115",
        name: "Employee Advances",
        nameAr: "سلف الموظفين",
        type: AccountType.ASSET,
        subType: AccountSubType.RECEIVABLE,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Cash advances given to employees",
    },
    "1116": {
        code: "1116",
        name: "Retention Receivable",
        nameAr: "مبالغ محجوزة - مستحقة",
        type: AccountType.ASSET,
        subType: AccountSubType.RECEIVABLE,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Customer retention holdbacks withheld until project sign-off",
    },
    "1120": {
        code: "1120",
        name: "VAT Receivable (Input VAT)",
        nameAr: "ضريبة القيمة المضافة المستردة",
        type: AccountType.ASSET,
        subType: AccountSubType.RECEIVABLE,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "VAT paid on purchases recoverable from tax authority",
    },
    "1121": {
        code: "1121",
        name: "Provision - Doubtful Debts",
        nameAr: "مخصص الديون المشكوك فيها",
        type: AccountType.CONTRA_ASSET,
        subType: AccountSubType.RECEIVABLE,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Allowance for bad debts",
    },


    // Prepaid & Deposits (1130-1140)
    "1130": {
        code: "1130",
        name: "Prepaid Expenses",
        nameAr: "مصروفات مدفوعة مقدماً",
        type: AccountType.ASSET,
        subType: AccountSubType.PREPAID,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Payments made in advance for future expenses",
    },
    "1140": {
        code: "1140",
        name: "Security Deposits",
        nameAr: "تأمينات مدفوعة",
        type: AccountType.ASSET,
        subType: AccountSubType.PREPAID,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Refundable deposits paid to landlords or suppliers",
    },

    // Raw Materials Inventory (1201-1203)
    "1201": {
        code: "1201",
        name: "Raw Materials - Fabric",
        nameAr: "مخزون الأقمشة",
        type: AccountType.ASSET,
        subType: AccountSubType.INVENTORY,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Fabric stock used in garment production",
    },
    "1202": {
        code: "1202",
        name: "Raw Materials - Accessories",
        nameAr: "مخزون الإكسسوارات",
        type: AccountType.ASSET,
        subType: AccountSubType.INVENTORY,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Buttons, zippers, threads and accessories",
    },
    "1203": {
        code: "1203",
        name: "Packaging Materials",
        nameAr: "مخزون مواد التعبئة",
        type: AccountType.ASSET,
        subType: AccountSubType.INVENTORY,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Boxes, bags, labels and packaging supplies",
    },
    "1204": {
        code: "1204",
        name: "Raw Materials - In Transit",
        nameAr: "مواد خام في الطريق",
        type: AccountType.ASSET,
        subType: AccountSubType.INVENTORY,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Goods not yet received",
    },
    "1205": {
        code: "1205",
        name: "Raw Materials - Scrap",
        nameAr: "مخزون الخردة",
        type: AccountType.ASSET,
        subType: AccountSubType.INVENTORY,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Scrap inventory",
    },

    // Work in Progress & Finished Goods (1210-1240)
    "1210": {
        code: "1210",
        name: "Work in Progress (WIP) - Control",
        nameAr: "إنتاج تحت التشغيل",
        type: AccountType.ASSET,
        subType: AccountSubType.INVENTORY,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "WIP summary control account — detailed balances in 1710-1713 sub-accounts",
    },
    "1710": {
        code: "1710",
        name: "WIP - Materials",
        nameAr: "WIP - المواد",
        type: AccountType.ASSET,
        subType: AccountSubType.INVENTORY,
        normalBalance: "debit",
        parentCode: "1210",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Materials in production",
    },
    "1711": {
        code: "1711",
        name: "WIP - Labor",
        nameAr: "WIP - العمالة",
        type: AccountType.ASSET,
        subType: AccountSubType.INVENTORY,
        normalBalance: "debit",
        parentCode: "1210",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Labor in production",
    },
    "1712": {
        code: "1712",
        name: "WIP - Overhead",
        nameAr: "WIP - التكاليف غير المباشرة",
        type: AccountType.ASSET,
        subType: AccountSubType.INVENTORY,
        normalBalance: "debit",
        parentCode: "1210",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Overhead in production",
    },
    "1713": {
        code: "1713",
        name: "WIP - Outside Processing",
        nameAr: "مصنعية الغير",
        type: AccountType.ASSET,
        subType: AccountSubType.INVENTORY,
        normalBalance: "debit",
        parentCode: "1210",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Subcontracted / outsourced processing costs",
    },
    "1220": {
        code: "1220",
        name: "Finished Goods",
        nameAr: "مخزون البضاعة الجاهزة",
        type: AccountType.ASSET,
        subType: AccountSubType.INVENTORY,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Completed products ready for sale or delivery",
    },
    "1221": {
        code: "1221",
        name: "Finished Goods - Reserved",
        nameAr: "بضاعة جاهزة - محجوزة",
        type: AccountType.ASSET,
        subType: AccountSubType.INVENTORY,
        normalBalance: "debit",
        parentCode: "1220",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Allocated to orders",
    },
    "1222": {
        code: "1222",
        name: "Finished Goods - Returns",
        nameAr: "بضاعة جاهزة - مرتجعة",
        type: AccountType.ASSET,
        subType: AccountSubType.INVENTORY,
        normalBalance: "debit",
        parentCode: "1220",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Returned goods",
    },
    "1240": {
        code: "1240",
        name: "Inventory Adjustments",
        nameAr: "تسويات المخزون",
        type: AccountType.ASSET,
        subType: AccountSubType.INVENTORY,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Clearing account for inventory count adjustments",
    },
    "1241": {
        code: "1241",
        name: "Allowance for Inventory Obsolescence",
        nameAr: "مخصص هبوط قيمة المخزون",
        type: AccountType.CONTRA_ASSET,
        subType: AccountSubType.INVENTORY,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Provision for inventory written down to net realisable value (IAS 2.9)",
    },
    "1230": {
        code: "1230",
        name: "Samples & Prototypes",
        nameAr: "العينات والنماذج",
        type: AccountType.ASSET,
        subType: AccountSubType.INVENTORY,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Sample pieces and prototypes for design/testing",
    },

    // Fixed Assets - Machinery (1301-1307)
    "1301": {
        code: "1301",
        name: "Sewing Machines",
        nameAr: "ماكينات الخياطة",
        type: AccountType.ASSET,
        subType: AccountSubType.FIXED_ASSET,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Industrial sewing machines used in production",
    },
    "1302": {
        code: "1302",
        name: "Cutting Machines",
        nameAr: "ماكينات القص",
        type: AccountType.ASSET,
        subType: AccountSubType.FIXED_ASSET,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Fabric cutting equipment",
    },
    "1303": {
        code: "1303",
        name: "Production Equipment",
        nameAr: "معدات الإنتاج",
        type: AccountType.ASSET,
        subType: AccountSubType.FIXED_ASSET,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Other factory equipment and tools",
    },
    "1304": {
        code: "1304",
        name: "Office Equipment",
        nameAr: "معدات المكتب",
        type: AccountType.ASSET,
        subType: AccountSubType.FIXED_ASSET,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Printers, devices and office tools",
    },
    "1305": {
        code: "1305",
        name: "Computers & Tablets",
        nameAr: "أجهزة الحاسب الآلي",
        type: AccountType.ASSET,
        subType: AccountSubType.FIXED_ASSET,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Computers and tablets used by staff",
    },
    "1306": {
        code: "1306",
        name: "Furniture & Fixtures",
        nameAr: "الأثاث والتجهيزات",
        type: AccountType.ASSET,
        subType: AccountSubType.FIXED_ASSET,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Desks, shelves and office furniture",
    },
    "1307": {
        code: "1307",
        name: "Vehicles",
        nameAr: "وسائل النقل",
        type: AccountType.ASSET,
        subType: AccountSubType.FIXED_ASSET,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Company cars or delivery vehicles",
    },

    // Accumulated Depreciation (1351-1354)
    "1351": {
        code: "1351",
        name: "Accum Dep - Machines",
        nameAr: "مجمع إهلاك الماكينات",
        type: AccountType.CONTRA_ASSET,
        subType: AccountSubType.DEPRECIATION,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Accumulated depreciation of machines",
    },
    "1352": {
        code: "1352",
        name: "Accum Dep - Equipment",
        nameAr: "مجمع إهلاك المعدات",
        type: AccountType.CONTRA_ASSET,
        subType: AccountSubType.DEPRECIATION,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Accumulated depreciation of equipment",
    },
    "1353": {
        code: "1353",
        name: "Accum Dep - Furniture",
        nameAr: "مجمع إهلاك الأثاث",
        type: AccountType.CONTRA_ASSET,
        subType: AccountSubType.DEPRECIATION,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Accumulated depreciation of furniture",
    },
    "1354": {
        code: "1354",
        name: "Accum Dep - Vehicles",
        nameAr: "مجمع إهلاك السيارات",
        type: AccountType.CONTRA_ASSET,
        subType: AccountSubType.DEPRECIATION,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Accumulated depreciation of vehicles",
    },

    // Intangible Assets (1401-1405)
    "1402": {
        code: "1402",
        name: "ERP / Systems",
        nameAr: "أنظمة تخطيط الموارد",
        type: AccountType.ASSET,
        subType: AccountSubType.INTANGIBLE,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Business systems and ERP development costs",
    },
    "1451": {
        code: "1451",
        name: "Domain Names & Websites",
        nameAr: "أسماء النطاقات والمواقع",
        type: AccountType.ASSET,
        subType: AccountSubType.INTANGIBLE,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Registered domains and business websites",
    },
    "1452": {
        code: "1452",
        name: "Software Licenses",
        nameAr: "تراخيص البرامج الرقمية",
        type: AccountType.ASSET,
        subType: AccountSubType.INTANGIBLE,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Permanent software licenses and subscriptions",
    },
    "1453": {
        code: "1453",
        name: "Digital Designs & IP",
        nameAr: "التصاميم الرقمية والملكية الفكرية",
        type: AccountType.ASSET,
        subType: AccountSubType.INTANGIBLE,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Proprietary digital designs, patterns and trademarks",
    },
    "1454": {
        code: "1454",
        name: "Cryptocurrency Holdings",
        nameAr: "حيازات العملات الرقمية",
        type: AccountType.ASSET,
        subType: AccountSubType.CASH,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: true,
        description: "Business crypto holdings (BTC, ETH, etc.)",
    },
    "1455": {
        code: "1455",
        name: "NFT Assets",
        nameAr: "الأصول الرقمية NFT",
        type: AccountType.ASSET,
        subType: AccountSubType.CASH,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Non-fungible tokens owned by the company",
    },
    "1456": {
        code: "1456",
        name: "Social Media Accounts",
        nameAr: "حسابات التواصل الاجتماعي",
        type: AccountType.ASSET,
        subType: AccountSubType.INTANGIBLE,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Valued social media presence and accounts",
    },
    "1491": {
        code: "1491",
        name: "Accum Amortization - Intangibles",
        nameAr: "مجمع إطفاء الأصول غير الملموسة",
        type: AccountType.CONTRA_ASSET,
        subType: AccountSubType.DEPRECIATION,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Amortization of intangible assets",
    },


    // ============================================
    // LIABILITIES (2xxx)
    // ============================================

    // Payables (2101-2140)
    "2101": {
        code: "2101",
        name: "Accounts Payable - Suppliers",
        nameAr: "الموردون - ذمم دائنة",
        type: AccountType.LIABILITY,
        subType: AccountSubType.PAYABLE,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Amounts owed to suppliers for purchases",
    },
    "2102": {
        code: "2102",
        name: "Supplier Advances",
        nameAr: "دفعات مقدمة للموردين",
        type: AccountType.LIABILITY,
        subType: AccountSubType.PAYABLE,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Prepayments to suppliers",
    },
    "2105": {
        code: "2105",
        name: "Customer Deposits (MTO)",
        nameAr: "دفعات مقدمة من العملاء",
        type: AccountType.LIABILITY,
        subType: AccountSubType.PAYABLE,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Advance payments from customers",
    },
    "2110": {
        code: "2110",
        name: "VAT Payable (Output VAT)",
        nameAr: "ضريبة القيمة المضافة المستحقة",
        type: AccountType.LIABILITY,
        subType: AccountSubType.TAX_PAYABLE,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "VAT collected from customers to remit to authority",
    },
    "2111": {
        code: "2111",
        name: "VAT Clearing / Suspense",
        nameAr: "مقاصة ضريبة القيمة المضافة",
        type: AccountType.LIABILITY,
        subType: AccountSubType.TAX_PAYABLE,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Temporary account during VAT reconciliation",
    },
    "2112": {
        code: "2112",
        name: "VAT Payable to ETA (Net)",
        nameAr: "ضريبة القيمة المضافة المستحقة للاستحقاق",
        type: AccountType.LIABILITY,
        subType: AccountSubType.TAX_PAYABLE,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Net VAT owed to Egyptian Tax Authority",
    },
    "2115": {
        code: "2115",
        name: "Payroll Payable",
        nameAr: "الرواتب المستحقة",
        type: AccountType.LIABILITY,
        subType: AccountSubType.PAYABLE,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Salaries owed but not yet paid",
    },

    // IFRS 15 Contract Accounts (2117-2118)
    "2117": {
        code: "2117",
        name: "Retention Payable",
        nameAr: "تأمين ضمان محتجز مستحق",
        type: AccountType.LIABILITY,
        subType: AccountSubType.PAYABLE,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Retention held from subcontractors",
    },
    "2118": {
        code: "2118",
        name: "Contract Liability - Overbilling",
        nameAr: "التزام عقد - الفوترة الزائدة",
        type: AccountType.LIABILITY,
        subType: AccountSubType.PAYABLE,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "IFRS 15: Billed amount exceeds % complete earned",
    },
    "2120": {
        code: "2120",
        name: "Wages Payable - Production",
        nameAr: "أجور الإنتاج المستحقة",
        type: AccountType.LIABILITY,
        subType: AccountSubType.PAYABLE,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Factory labor wages accrued",
    },
    "2130": {
        code: "2130",
        name: "Tax Payable",
        nameAr: "الضرائب المستحقة",
        type: AccountType.LIABILITY,
        subType: AccountSubType.TAX_PAYABLE,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Corporate or other taxes owed",
    },
    "2140": {
        code: "2140",
        name: "Accrued Expenses",
        nameAr: "مصروفات مستحقة",
        type: AccountType.LIABILITY,
        subType: AccountSubType.ACCRUED,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Expenses incurred but not invoiced",
    },
    "2150": {
        code: "2150",
        name: "Provision - Expenses",
        nameAr: "مخصصات المصروفات",
        type: AccountType.LIABILITY,
        subType: AccountSubType.ACCRUED,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "General provisions",
    },
    "2155": {
        code: "2155",
        name: "Provision - Onerous Contracts",
        nameAr: "مخصص عقود خاسرة",
        type: AccountType.LIABILITY,
        subType: AccountSubType.ACCRUED,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "IAS 37: Expected loss when total costs exceed contract price",
    },
    "2160": {
        code: "2160",
        name: "Statutory Deductions Payable",
        nameAr: "استقطاعات حكومية مستحقة",
        type: AccountType.LIABILITY,
        subType: AccountSubType.TAX_PAYABLE,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Social insurance and other deductions",
    },

    // Loans (2201-2210)
    "2201": {
        code: "2201",
        name: "Short-term Loans",
        nameAr: "قروض قصيرة الأجل",
        type: AccountType.LIABILITY,
        subType: AccountSubType.LOAN,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Loans due within one year",
    },
    "2210": {
        code: "2210",
        name: "Long-term Loans",
        nameAr: "قروض طويلة الأجل",
        type: AccountType.LIABILITY,
        subType: AccountSubType.LOAN,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Loans due after one year",
    },

    // ============================================
    // EQUITY (3xxx)
    // ============================================
    "3001": {
        code: "3001",
        name: "Owner Capital",
        nameAr: "رأس المال",
        type: AccountType.EQUITY,
        subType: AccountSubType.CAPITAL,
        normalBalance: "credit",
        isActive: false,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Owner investments into the business",
        deprecatedReason: "Replaced by partner capital accounts 3011/3012/3013"
    },
    "3002": {
        code: "3002",
        name: "Owner Drawings",
        nameAr: "المسحوبات الشخصية",
        type: AccountType.EQUITY,
        subType: AccountSubType.CAPITAL,
        normalBalance: "debit",
        isActive: false,
        isSystemAccount: true,
        isCashFlowTracked: true,
        description: "Owner withdrawals from business funds",
        deprecatedReason: "Replaced by partner drawings accounts 3021/3022/3023"
    },
    "3011": {
        code: "3011",
        name: "Capital — Ahmed (60%)",
        nameAr: "رأس مال - أحمد",
        type: AccountType.EQUITY,
        subType: AccountSubType.CAPITAL,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Partner 1 Capital Account",
    },
    "3012": {
        code: "3012",
        name: "Capital — Ibrahim (25%)",
        nameAr: "رأس مال - إبراهيم",
        type: AccountType.EQUITY,
        subType: AccountSubType.CAPITAL,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Partner 2 Capital Account",
    },
    "3013": {
        code: "3013",
        name: "Capital — Fathy (15%)",
        nameAr: "رأس مال - فتحي",
        type: AccountType.EQUITY,
        subType: AccountSubType.CAPITAL,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Partner 3 Capital Account",
    },
    "3021": {
        code: "3021",
        name: "Drawings — Ahmed",
        nameAr: "مسحوبات - أحمد",
        type: AccountType.EQUITY,
        subType: AccountSubType.CAPITAL,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: true,
        description: "Ahmed Contradrawings Account",
    },
    "3022": {
        code: "3022",
        name: "Drawings — Ibrahim",
        nameAr: "مسحوبات - إبراهيم",
        type: AccountType.EQUITY,
        subType: AccountSubType.CAPITAL,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: true,
        description: "Ibrahim Contradrawings Account",
    },
    "3023": {
        code: "3023",
        name: "Drawings — Fathy",
        nameAr: "مسحوبات - فتحي",
        type: AccountType.EQUITY,
        subType: AccountSubType.CAPITAL,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: true,
        description: "Fathy Contradrawings Account",
    },
    "3100": {
        code: "3100",
        name: "Retained Earnings",
        nameAr: "الأرباح المحتجزة",
        type: AccountType.EQUITY,
        subType: AccountSubType.RETAINED_EARNINGS,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Accumulated profits from previous years",
    },
    "3200": {
        code: "3200",
        name: "Current Year Profit/Loss",
        nameAr: "أرباح/خسائر السنة الحالية",
        type: AccountType.EQUITY,
        subType: AccountSubType.RETAINED_EARNINGS,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Current year net income or loss",
    },

    // ============================================
    // REVENUE (4xxx)
    // ============================================
    "4001": {
        code: "4001",
        name: "Product Sales - Retail",
        nameAr: "مبيعات التجزئة",
        type: AccountType.REVENUE,
        subType: AccountSubType.SALES,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Sales to individual retail customers",
    },
    "4002": {
        code: "4002",
        name: "Product Sales - Wholesale",
        nameAr: "مبيعات الجملة",
        type: AccountType.REVENUE,
        subType: AccountSubType.SALES,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Bulk sales to resellers",
    },
    "4003": {
        code: "4003",
        name: "Custom MTO Orders",
        nameAr: "الطلبات المخصصة",
        type: AccountType.REVENUE,
        subType: AccountSubType.SALES,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Make-to-order customized garment sales",
    },
    "4004": {
        code: "4004",
        name: "Revenue - Over-Time (POC)",
        nameAr: "إيرادات محتسبة بنسبة الإنجاز",
        type: AccountType.REVENUE,
        subType: AccountSubType.SALES,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "IFRS 15: Revenue recognized over time (percentage-of-completion)",
    },
    "4010": {
        code: "4010",
        name: "Alteration/Service Revenue",
        nameAr: "إيرادات التعديلات",
        type: AccountType.REVENUE,
        subType: AccountSubType.SERVICE,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Alteration or tailoring service revenue",
    },
    "4011": {
        code: "4011",
        name: "Online Sales",
        nameAr: "المبيعات الإلكترونية",
        type: AccountType.REVENUE,
        subType: AccountSubType.SALES,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "E-commerce revenue",
    },
    "4012": {
        code: "4012",
        name: "Export Sales",
        nameAr: "مبيعات التصدير",
        type: AccountType.REVENUE,
        subType: AccountSubType.SALES,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Export revenue",
    },
    "4020": {
        code: "4020",
        name: "Other Income",
        nameAr: "إيرادات أخرى",
        type: AccountType.REVENUE,
        subType: AccountSubType.OTHER_INCOME,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Non-core miscellaneous income",
    },

    // Contra Revenue (4090-4091)
    "4090": {
        code: "4090",
        name: "Sales Discounts",
        nameAr: "خصم المبيعات",
        type: AccountType.CONTRA_REVENUE,
        subType: AccountSubType.SALES,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Discounts granted to customers",
    },
    "4091": {
        code: "4091",
        name: "Sales Returns",
        nameAr: "مردودات المبيعات",
        type: AccountType.CONTRA_REVENUE,
        subType: AccountSubType.SALES,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Returned goods reducing revenue",
    },

    // ============================================
    // COST OF GOODS SOLD (5xxx)
    // ============================================
    "5001": {
        code: "5001",
        name: "Raw Materials Used",
        nameAr: "المواد الخام المستخدمة",
        type: AccountType.COGS,
        subType: AccountSubType.MATERIALS,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Materials consumed in production",
    },
    "5002": {
        code: "5002",
        name: "Direct Labor - Production",
        nameAr: "أجور العمال المباشرة",
        type: AccountType.COGS,
        subType: AccountSubType.LABOR,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Factory workers wages",
    },
    "5003": {
        code: "5003",
        name: "Production Overtime",
        nameAr: "أجور العمل الإضافي",
        type: AccountType.COGS,
        subType: AccountSubType.LABOR,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Overtime wages for production",
    },
    "5004": {
        code: "5004",
        name: "Manufacturing Overhead",
        nameAr: "تكاليف صناعية غير مباشرة",
        type: AccountType.COGS,
        subType: AccountSubType.OVERHEAD,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Indirect factory costs",
    },
    "5005": {
        code: "5005",
        name: "Factory Rent",
        nameAr: "إيجار المصنع",
        type: AccountType.COGS,
        subType: AccountSubType.OVERHEAD,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Factory facility rent expense",
    },
    "5006": {
        code: "5006",
        name: "Factory Utilities",
        nameAr: "مرافق المصنع",
        type: AccountType.COGS,
        subType: AccountSubType.OVERHEAD,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Electricity and water for production",
    },
    "5007": {
        code: "5007",
        name: "Machine Maintenance",
        nameAr: "صيانة الماكينات",
        type: AccountType.COGS,
        subType: AccountSubType.OVERHEAD,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Maintenance and repairs of machines",
    },
    "5008": {
        code: "5008",
        name: "Depreciation - Factory Equipment",
        nameAr: "إهلاك معدات المصنع",
        type: AccountType.COGS,
        subType: AccountSubType.OVERHEAD,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Depreciation of factory assets",
    },

    // Overhead Control & Applied (5009-5011)
    "5009": {
        code: "5009",
        name: "Manufacturing OH - Applied",
        nameAr: "تحميل التكاليف الصناعية المقدرة",
        type: AccountType.COGS,
        subType: AccountSubType.OVERHEAD,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Overhead applied to WIP via POHR (credit balance)",
    },
    "5010": {
        code: "5010",
        name: "Manufacturing OH - Control",
        nameAr: "مراقبة التكاليف الصناعية الفعلية",
        type: AccountType.COGS,
        subType: AccountSubType.OVERHEAD,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Actual indirect manufacturing costs incurred",
    },
    "5011": {
        code: "5011",
        name: "Over/Under-Applied OH",
        nameAr: "فرق تحميل التكاليف الصناعية",
        type: AccountType.COGS,
        subType: AccountSubType.OVERHEAD,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Disposal account for OH variance (debit = under-applied, credit = over-applied)",
    },


    // Manufacturing Cost Accounts (5101-5301)


    // Variance Analysis Accounts (5201-5223)
    "5201": {
        code: "5201",
        name: "Material Price Variance",
        nameAr: "فرق سعر المواد",
        type: AccountType.COGS,
        subType: AccountSubType.MATERIALS,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Unfavorable = debit, Favorable = credit",
    },
    "5202": {
        code: "5202",
        name: "Material Usage Variance",
        nameAr: "فرق استخدام المواد",
        type: AccountType.COGS,
        subType: AccountSubType.MATERIALS,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Unfavorable = debit, Favorable = credit",
    },
    "5211": {
        code: "5211",
        name: "Labor Rate Variance",
        nameAr: "فرق معدل الأجور",
        type: AccountType.COGS,
        subType: AccountSubType.LABOR,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Unfavorable = debit, Favorable = credit",
    },
    "5212": {
        code: "5212",
        name: "Labor Efficiency Variance",
        nameAr: "فرق كفاءة الأجور",
        type: AccountType.COGS,
        subType: AccountSubType.LABOR,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Unfavorable = debit, Favorable = credit",
    },
    "5221": {
        code: "5221",
        name: "OH Spending Variance",
        nameAr: "فرق إنفاق التكاليف الصناعية",
        type: AccountType.COGS,
        subType: AccountSubType.OVERHEAD,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Unfavorable = debit, Favorable = credit",
    },
    "5222": {
        code: "5222",
        name: "OH Efficiency Variance",
        nameAr: "فرق كفاءة التكاليف الصناعية",
        type: AccountType.COGS,
        subType: AccountSubType.OVERHEAD,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Unfavorable = debit, Favorable = credit",
    },
    "5223": {
        code: "5223",
        name: "OH Volume Variance",
        nameAr: "فرق حجم التكاليف الصناعية",
        type: AccountType.COGS,
        subType: AccountSubType.OVERHEAD,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Unfavorable = debit, Favorable = credit",
    },

    // COGM / Standard Cost Summary (5300-5302)
    "5300": {
        code: "5300",
        name: "Cost of Goods Manufactured (COGM)",
        nameAr: "تكلفة البضاعة المصنعة",
        type: AccountType.COGS,
        subType: AccountSubType.MATERIALS,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Summary account for DM + DL + OH transferred from WIP to FG",
    },
    "5301": {
        code: "5301",
        name: "Cost of Goods Sold",
        nameAr: "تكلفة البضاعة المباعة",
        type: AccountType.COGS,
        subType: AccountSubType.MATERIALS,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Actual COGS (goods shipped/sold)",
    },
    "5302": {
        code: "5302",
        name: "Standard Cost of Goods Sold",
        nameAr: "تكلفة البضاعة المباعة المعيارية",
        type: AccountType.COGS,
        subType: AccountSubType.MATERIALS,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "COGS initially recorded at standard cost (adjusted via variances)",
    },

    // ============================================
    // OPERATING EXPENSES (6xxx)
    // ============================================
    "6001": {
        code: "6001",
        name: "Office Salaries",
        nameAr: "رواتب المكتب",
        type: AccountType.EXPENSE,
        subType: AccountSubType.ADMINISTRATIVE,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Administrative staff salaries",
    },
    "6002": {
        code: "6002",
        name: "Office Rent",
        nameAr: "إيجار المكتب",
        type: AccountType.EXPENSE,
        subType: AccountSubType.ADMINISTRATIVE,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Office rental payments",
    },
    "6003": {
        code: "6003",
        name: "Internet & Telecom",
        nameAr: "الإنترنت والاتصالات",
        type: AccountType.EXPENSE,
        subType: AccountSubType.ADMINISTRATIVE,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Internet and phone bills",
    },
    "6004": {
        code: "6004",
        name: "Software Subscriptions",
        nameAr: "اشتراكات البرامج",
        type: AccountType.EXPENSE,
        subType: AccountSubType.ADMINISTRATIVE,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Monthly software services",
    },
    "6005": {
        code: "6005",
        name: "Office Supplies",
        nameAr: "مستلزمات مكتبية",
        type: AccountType.EXPENSE,
        subType: AccountSubType.ADMINISTRATIVE,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Stationery and office materials",
    },
    "6006": {
        code: "6006",
        name: "Professional Fees",
        nameAr: "أتعاب مهنية",
        type: AccountType.EXPENSE,
        subType: AccountSubType.ADMINISTRATIVE,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Legal and accounting services",
    },
    "6007": {
        code: "6007",
        name: "Depreciation - Office Equipment",
        nameAr: "إهلاك معدات المكتب",
        type: AccountType.EXPENSE,
        subType: AccountSubType.ADMINISTRATIVE,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Depreciation for office assets",
    },

    // Marketing Expenses (6101-6107)
    "6101": {
        code: "6101",
        name: "Marketing Expense",
        nameAr: "مصاريف التسويق",
        type: AccountType.EXPENSE,
        subType: AccountSubType.MARKETING,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "General marketing activities",
    },
    "6102": {
        code: "6102",
        name: "Advertising",
        nameAr: "الإعلانات",
        type: AccountType.EXPENSE,
        subType: AccountSubType.MARKETING,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Paid ads and campaigns",
    },
    "6103": {
        code: "6103",
        name: "Photoshoots & Content Production",
        nameAr: "التصوير وإنتاج المحتوى",
        type: AccountType.EXPENSE,
        subType: AccountSubType.MARKETING,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Media production for branding",
    },
    "6104": {
        code: "6104",
        name: "Influencer & Campaign Costs",
        nameAr: "تكاليف المؤثرين",
        type: AccountType.EXPENSE,
        subType: AccountSubType.MARKETING,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Influencer and promotional costs",
    },
    "6105": {
        code: "6105",
        name: "Packaging Expense",
        nameAr: "مصاريف التعبئة",
        type: AccountType.EXPENSE,
        subType: AccountSubType.MARKETING,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Packaging used for sold products",
    },
    "6106": {
        code: "6106",
        name: "Delivery & Shipping",
        nameAr: "مصاريف التوصيل والشحن",
        type: AccountType.EXPENSE,
        subType: AccountSubType.OPERATING,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Courier and delivery costs",
    },
    "6107": {
        code: "6107",
        name: "Commissions",
        nameAr: "العمولات",
        type: AccountType.EXPENSE,
        subType: AccountSubType.OPERATING,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Sales commissions",
    },

    // Other Operating Expenses (6201-6206)
    "6108": {
        code: "6108",
        name: "E-commerce Platform Fees",
        nameAr: "رسوم منصات التجارة الإلكترونية",
        type: AccountType.EXPENSE,
        subType: AccountSubType.OPERATING,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Shopify, WooCommerce, and other e-commerce site monthly/transactional fees",
    },
    "6109": {
        code: "6109",
        name: "Payment Gateway Fees",
        nameAr: "رسوم بوابات الدفع",
        type: AccountType.EXPENSE,
        subType: AccountSubType.FINANCIAL,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Payment gateway transaction processing fees (Stripe, PayMob, etc.)",
    },
    "6110": {
        code: "6110",
        name: "Marketplace Commission",
        nameAr: "عمولات المنصات",
        type: AccountType.EXPENSE,
        subType: AccountSubType.OPERATING,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Sales commissions for third-party marketplaces (Amazon, Noon, etc.)",
    },
    "6201": {
        code: "6201",
        name: "Travel & Transportation",
        nameAr: "السفر والمواصلات",
        type: AccountType.EXPENSE,
        subType: AccountSubType.OPERATING,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Business travel costs",
    },
    "6202": {
        code: "6202",
        name: "Bank Fees",
        nameAr: "مصاريف بنكية",
        type: AccountType.EXPENSE,
        subType: AccountSubType.FINANCIAL,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Bank service charges",
    },
    "6203": {
        code: "6203",
        name: "Repairs & Maintenance",
        nameAr: "الإصلاحات والصيانة",
        type: AccountType.EXPENSE,
        subType: AccountSubType.OPERATING,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "General maintenance expenses",
    },
    "6204": {
        code: "6204",
        name: "Cleaning Services",
        nameAr: "خدمات النظافة",
        type: AccountType.EXPENSE,
        subType: AccountSubType.OPERATING,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Cleaning and housekeeping services",
    },
    "6205": {
        code: "6205",
        name: "Insurance",
        nameAr: "التأمين",
        type: AccountType.EXPENSE,
        subType: AccountSubType.OPERATING,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Insurance premiums",
    },
    "6206": {
        code: "6206",
        name: "Miscellaneous Expenses",
        nameAr: "مصروفات متنوعة",
        type: AccountType.EXPENSE,
        subType: AccountSubType.OPERATING,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Other small expenses",
    },

    // ============================================
    // OTHER INCOME/EXPENSES (7xxx)
    // ============================================
    "6209": {
        code: "6209",
        name: "Rework & Abnormal Spoilage",
        nameAr: "تكاليف إعادة الإنتاج والهالك غير الطبيعي",
        type: AccountType.EXPENSE,
        subType: AccountSubType.OPERATING,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Abnormal spoilage and rework costs expensed as period costs (IAS 2.16)",
    },
    "6210": {
        code: "6210",
        name: "Inventory Write-down to NRV",
        nameAr: "هبوط قيمة المخزون إلى صافي القيمة القابلة للتحقق",
        type: AccountType.EXPENSE,
        subType: AccountSubType.OPERATING,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Expense when inventory cost exceeds net realisable value (IAS 2.9)",
    },
    "6207": {
        code: "6207",
        name: "Inventory Shrinkage & Loss",
        nameAr: "نقص وفقد المخزون",
        type: AccountType.EXPENSE,
        subType: AccountSubType.OPERATING,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Losses from inventory count differences",
    },
    "6208": {
        code: "6208",
        name: "Inventory Gain / Count Surplus",
        nameAr: "أرباح / فوائض الجرد",
        type: AccountType.OTHER,
        subType: AccountSubType.OTHER_INCOME,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Gains from positive inventory count differences",
    },
    "7001": {
        code: "7001",
        name: "Interest Expense",
        nameAr: "مصروف الفوائد",
        type: AccountType.OTHER,
        subType: AccountSubType.FINANCIAL,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Interest paid on loans",
    },
    "7002": {
        code: "7002",
        name: "Penalties & Fines",
        nameAr: "الغرامات والجزاءات",
        type: AccountType.OTHER,
        subType: AccountSubType.FINANCIAL,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Government or contractual penalties",
    },
    "7003": {
        code: "7003",
        name: "Asset Disposal Gain/Loss",
        nameAr: "أرباح/خسائر بيع الأصول",
        type: AccountType.OTHER,
        subType: AccountSubType.OTHER_INCOME,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Gain or loss from selling assets",
    },
    "7005": {
        code: "7005",
        name: "Income Tax Expense",
        nameAr: "ضريبة الدخل",
        type: AccountType.OTHER,
        subType: AccountSubType.FINANCIAL,
        normalBalance: "debit",
        isActive: true,
        isSystemAccount: true,
        isCashFlowTracked: false,
        description: "Corporate income tax charge at 22.5% (Egypt standard rate)",
    },
    "7004": {
        code: "7004",
        name: "FX Gain/Loss",
        nameAr: "أرباح/خسائر فروق العملة",
        type: AccountType.OTHER,
        subType: AccountSubType.FINANCIAL,
        normalBalance: "credit",
        isActive: true,
        isSystemAccount: false,
        isCashFlowTracked: false,
        description: "Foreign exchange translation gains and losses per IAS 21",
    },
}

/**
 * Account code lookup for quick reference (backward compatible)
 */
export const ACCOUNT_CODES = {
    // Cash & Bank
    CASH_ON_HAND: "1101",
    PETTY_CASH: "1102",
    BANK_MAIN: "1103",
    BANK_SAVINGS: "1104",
    BANK_PAYROLL: "1105",
    BANK_PAYMENT_GATEWAY: "1106",
    CHEQUES_UNDER_COLLECTION: "1107",

    // Receivables
    CONTRACT_ASSET: "1113",
    ACCOUNTS_RECEIVABLE: "1110",
    EMPLOYEE_ADVANCES: "1115",
    RETENTION_RECEIVABLE: "1116",
    VAT_RECEIVABLE: "1120",
    PROVISION_DOUBTFUL_DEBTS: "1121",
    // 1122 REMOVED (Duplicate)
    // 1505 REMOVED (Duplicate/Asset Classification Fix)

    // Prepaid
    PREPAID_EXPENSES: "1130",
    SECURITY_DEPOSITS: "1140",
    // Intangible Contra
    ACCUM_DEP_INTANGIBLES: "1491",

    // Inventory
    INVENTORY_ADJUSTMENTS: "1240",
    ALLOWANCE_INVENTORY_OBSOLESCENCE: "1241",
    RAW_MATERIALS_FABRIC: "1201",
    RAW_MATERIALS_ACCESSORIES: "1202",
    PACKAGING_MATERIALS: "1203",
    IN_TRANSIT_INVENTORY: "1204",
    SCRAP_INVENTORY: "1205",
    INVENTORY_WIP: "1210",
    WIP_MATERIALS: "1710",
    WIP_LABOR: "1711",
    WIP_OVERHEAD: "1712",
    WIP_OUTSIDE_PROCESSING: "1713",
    INVENTORY_FINISHED_GOODS: "1220",
    FG_RETAIL: "1221",
    FG_WHOLESALE: "1222",
    SAMPLES_PROTOTYPES: "1230",

    // Fixed Assets
    SEWING_MACHINES: "1301",
    CUTTING_MACHINES: "1302",
    PRODUCTION_EQUIPMENT: "1303",
    OFFICE_EQUIPMENT: "1304",
    COMPUTERS: "1305",
    FURNITURE: "1306",
    VEHICLES: "1307",

    // Depreciation
    ACCUM_DEP_MACHINES: "1351",
    ACCUM_DEP_EQUIPMENT: "1352",
    ACCUM_DEP_FURNITURE: "1353",
    ACCUM_DEP_VEHICLES: "1354",

    // Intangible / Digital
    DOMAIN_NAMES_WEBSITES: "1451",
    SOFTWARE_LICENSES_INTANGIBLE: "1452",
    DIGITAL_DESIGNS_IP: "1453",
    CRYPTO_HOLDINGS: "1454",
    NFT_ASSETS: "1455",
    SOCIAL_MEDIA_ACCOUNTS: "1456",
    ACCUM_AMORT_INTANGIBLES: "1491",
    ERP_SYSTEMS: "1402",

    // Liabilities
    ACCOUNTS_PAYABLE: "2101",
    SUPPLIER_ADVANCES: "2102",
    CUSTOMER_DEPOSITS_LIABILITY: "2105",
    VAT_PAYABLE: "2110",
    VAT_CLEARING: "2111",
    VAT_PAYABLE_ETA: "2112",
    PAYROLL_PAYABLE: "2115",
    RETENTION_PAYABLE: "2117",
    CONTRACT_LIABILITY_OVERBILLING: "2118",
    STATUTORY_PAYABLE: "2160",
    WAGES_PAYABLE_PRODUCTION: "2120",
    TAX_PAYABLE: "2130",
    ACCRUED_EXPENSES: "2140",
    DEFERRED_REVENUE: "2150",
    PROVISION_ONEROUS_CONTRACTS: "2155",
    SHORT_TERM_LOANS: "2201",
    LONG_TERM_LOANS: "2210",

    // Equity
    CAPITAL_AHMED: "3011",
    CAPITAL_IBRAHIM: "3012",
    CAPITAL_FATHY: "3013",
    DRAWINGS_AHMED: "3021",
    DRAWINGS_IBRAHIM: "3022",
    DRAWINGS_FATHY: "3023",
    RETAINED_EARNINGS: "3100",
    CURRENT_YEAR_PL: "3200",

    // Revenue
    SALES_RETAIL: "4001",
    SALES_WHOLESALE: "4002",
    SALES_CUSTOM_MTO: "4003",
    SALES_OVER_TIME_POC: "4004",
    SERVICE_REVENUE: "4010",
    ONLINE_SALES: "4011",
    EXPORT_SALES: "4012",
    OTHER_INCOME: "4020",
    SALES_DISCOUNTS: "4090",
    SALES_RETURNS: "4091",

    // COGS
    RAW_MATERIALS_USED: "5001",
    DIRECT_LABOR: "5002",
    PRODUCTION_OVERTIME: "5003",
    MANUFACTURING_OVERHEAD: "5004",
    FACTORY_RENT: "5005",
    FACTORY_UTILITIES: "5006",
    MACHINE_MAINTENANCE: "5007",
    DEPRECIATION_FACTORY: "5008",
    OH_APPLIED: "5009",
    OH_CONTROL: "5010",
    OH_VARIANCE: "5011",
    // Variance accounts (5201-5223)
    MATERIAL_PRICE_VARIANCE: "5201",
    MATERIAL_USAGE_VARIANCE: "5202",
    LABOR_RATE_VARIANCE: "5211",
    LABOR_EFFICIENCY_VARIANCE: "5212",
    OH_SPENDING_VARIANCE: "5221",
    OH_EFFICIENCY_VARIANCE: "5222",
    OH_VOLUME_VARIANCE: "5223",
    // COGM / Standard COGS
    COST_OF_GOODS_MANUFACTURED: "5300",
    COST_OF_GOODS_SOLD: "5301",
    STANDARD_COST_OF_GOODS_SOLD: "5302",

    // Operating Expenses
    OFFICE_SALARIES: "6001",
    OFFICE_RENT: "6002",
    INTERNET_TELECOM: "6003",
    SOFTWARE_SUBSCRIPTIONS: "6004",
    OFFICE_SUPPLIES: "6005",
    PROFESSIONAL_FEES: "6006",
    DEPRECIATION_OFFICE: "6007",
    MARKETING_EXPENSE: "6101",
    ADVERTISING: "6102",
    DELIVERY_SHIPPING: "6106",
    SALES_COMMISSIONS: "6107",
    ECOMMERCE_PLATFORM_FEES: "6108",
    PAYMENT_GATEWAY_FEES: "6109",
    MARKETPLACE_COMMISSION: "6110",
    BANK_FEES: "6202",
    INVENTORY_SHRINKAGE_LOSS: "6207",
    INVENTORY_GAIN_SURPLUS: "6208",
    REWORK_SPOILAGE_EXPENSE: "6209",
    INVENTORY_WRITEDOWN_NRV: "6210",

    // Other
    INTEREST_EXPENSE: "7001",
    INCOME_TAX_EXPENSE: "7005",
    PENALTIES_FINES: "7002",
    FX_GAIN_LOSS: "7004",
} as const

/**
 * Get account by code
 */
export function getAccount(code: string): Account | undefined {
    return CHART_OF_ACCOUNTS[code]
}

/**
 * Get account name by code
 */
export function getAccountName(code: string): string {
    return CHART_OF_ACCOUNTS[code]?.name || `Unknown (${code})`
}

/**
 * Get all accounts of a specific type
 */
export function getAccountsByType(type: AccountType): Account[] {
    return Object.values(CHART_OF_ACCOUNTS).filter(a => a.type === type)
}

/**
 * Get child accounts of a parent
 */
export function getChildAccounts(parentCode: string): Account[] {
    return Object.values(CHART_OF_ACCOUNTS).filter(a => a.parentCode === parentCode)
}

/**
 * Check if account has debit normal balance
 */
export function isDebitNormalBalance(code: string): boolean {
    const account = CHART_OF_ACCOUNTS[code]
    return account?.normalBalance === "debit"
}

/**
 * Get accounts grouped by category for UI display
 */
export function getAccountsByCategory(): Record<string, Account[]> {
    const categories: Record<string, Account[]> = {
        "Cash & Bank": [],
        "Receivables": [],
        "Inventory": [],
        "Fixed Assets": [],
        "Accumulated Depreciation": [],
        "Intangibles": [],
        "Payables & Liabilities": [],
        "Equity": [],
        "Revenue": [],
        "COGS": [],
        "Operating Expenses": [],
        "Other": [],
    }

    for (const account of Object.values(CHART_OF_ACCOUNTS)) {
        const code = parseInt(account.code)

        if (code >= 1101 && code <= 1104) categories["Cash & Bank"].push(account)
        else if (code >= 1110 && code <= 1120 || code === 1505) categories["Receivables"].push(account)
        else if (code >= 1130 && code <= 1140) categories["Receivables"].push(account)
        else if (code >= 1201 && code <= 1240) categories["Inventory"].push(account)
        else if (code >= 1301 && code <= 1307) categories["Fixed Assets"].push(account)
        else if (code >= 1351 && code <= 1354) categories["Accumulated Depreciation"].push(account)
        else if (code >= 1401 && code <= 1491) categories["Intangibles"].push(account)
        else if (code >= 2101 && code <= 2210) categories["Payables & Liabilities"].push(account)
        else if (code >= 3001 && code <= 3200) categories["Equity"].push(account)
        else if (code >= 4001 && code <= 4099) categories["Revenue"].push(account)
        else if (code >= 5001 && code <= 5399) categories["COGS"].push(account)
        else if (code >= 6001 && code <= 6206) categories["Operating Expenses"].push(account)
        else categories["Other"].push(account)
    }

    return categories
}
