export const BREADCRUMB_LABELS: Record<string, string> = {
  customers: "Customers",
  designs: "Designs",
  "sales-orders": "Sales Orders",
  "work-orders": "Work Orders",
  inventory: "Inventory",
  invoices: "Invoices",
  expenses: "Expenses",
  assets: "Assets",
  liabilities: "Liabilities",
  payments: "Payments",
  reports: "Reports",
  "chart-of-accounts": "Chart of Accounts",
  "journal-entries": "Journal Entries",
  "background-jobs": "Background Jobs",
  accounting: "Accounting",
  setup: "Setup",
  "opening-balances": "Opening Balances",
  "api-docs": "API Documentation",
  vendors: "Vendors",
  "purchase-orders": "Purchase Orders",
  bom: "BOM Management",
  contracts: "IFRS 15 Contracts",
  variance: "Variance Analysis",
  overhead: "Overhead Configuration",
  "year-end-close": "Year-End Close",
}